version: '3'

services:
  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./redisdata:/data
  
  jupyter-worker:
    build:
      context: ./
      dockerfile: Dockerfile-devel
    environment:
      - LOGLEVEL=DEBUG
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL}
      - COPERNICUS_USERNAME=${COPERNICUS_USERNAME}
      - COPERNICUS_PWD=${COPERNICUS_PWD}
      - ASF_USERNAME=${ASF_USERNAME}
      - ASF_PWD=${ASF_PWD}
      - USGS_USERNAME=${USGS_USERNAME}
      - USGS_PWD=${USGS_PWD}
      - SEDAS_USERNAME=${SEDAS_USERNAME}
      - SEDAS_PWD=${SEDAS_PWD}  
    ports:
      - "8866:8888"
    volumes:
      - ./data:/tmp/data
      - ./workflows:/opt/notebooks
    restart: always
