version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - REDIS_SERVICE_HOST=
      - REDIS_SERVICE_PORT=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - AWS_ENDPOINT=
      - AWS_BUCKET=
    volumes:
      - ./src:/src
      - ./tests:/tests
