version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: landsat/Dockerfile
    network_mode: host
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_USGS_PROCESSED_CHANNEL=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_ENDPOINT=
      - S3_BUCKET=