version: '3'

services:
  redis-client:
    image: satapps/ard-workflow-job-insert:1.2.1
    container_name: job-inserter
    restart: on-failure:3
    networks:
      - modis-nbar_default
    environment:
      - REDIS_SERVICE_HOST=${REDIS_SERVICE_HOST}
    volumes:
      - ./work-items.txt:/var/opt/work-items.list

networks:
  modis-nbar_default:
    external: true
