apiVersion: v1
kind: Pod
metadata:
  name: job-inserter
  namespace: ard
spec:
  volumes:
    - name: ard-work-items
      configMap:
        name: ard-work-items
  initContainers:
    - name: init-job-inserter
      image: busybox:1.28
      command: ['sh', '-c', 'until nslookup redis-master; do echo Waiting for redis-master; sleep 2; done;']
  containers:
    - name: job-inserter
      image: satapps/ard-workflow-job-insert:1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: ard-work-items
          mountPath: /var/opt/work-items.list
          subPath: work-items.list
  restartPolicy: Never
