apiVersion: v1
kind: Pod
metadata:
  name: job-inserter
  namespace: ard
spec:
  volumes:
    - name: ard-work-items
      configMap:
        name: ard-work-items
  initContainers:
    - name: init-job-inserter
      image: busybox:1.28
      env:
        - name: REDIS_SERVICE_HOST
          value: "redis-master"
      command: ['sh', '-c', 'until nslookup $REDIS_SERVICE_HOST; do echo Waiting for redis-master; sleep 2; done;']
  containers:
    - name: job-inserter
      image: satapps/ard-workflow-job-insert:1.2.1
      imagePullPolicy: IfNotPresent
      env:
        - name: REDIS_SERVICE_HOST
          value: "redis-master"
      volumeMounts:
        - name: ard-work-items
          mountPath: /var/opt/work-items.list
          subPath: work-items.list
  restartPolicy: Never
